/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'atombrot' at '08.11.14 21:58' with Gradle 2.1
 *
 * @author atombrot, @date 08.11.14 21:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
